# Author: Catalin Constantin Usurelu
# Grupa: 333CA

#   Target
PROGRAM_spu := spu
LIBRARY_embed := lib_spu.a

IMPORTS :=  -lmisc -lm

# include partea care face toata treaba pe baza definitiilor de mai sus

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
